docker container
Tobias11111010110/Zoo-App pull request #10
Opened 2024-03-19 17:06 UTC by Tobias11111010110

2024-03-19 20:43 UTC, sigristjan requested changes
Ich würde die Kommentare vielleicht ein bisschen anders formulieren.
Anstatt z.B. "Verwenden Sie das Offizielle Node.js-Image..."->"Verwendet das Offizielle Node.js-Image als Basis"; also ohne das "Sie". Es klingt sonst als wäre es von chatgpt 😄

2024-03-19 20:43 UTC, sigristjan commented on Dockerfile-frontend
> +FROM node:14-alpine
Warum benutzt das die alpine Version und das Backend nicht?

2024-03-19 20:43 UTC, sigristjan commented on docker-compose.yml
> +      - 8080:3000 # Ändern Sie den Container-Port auf 3000, den Host-Port auf einen verfügbaren Port, z.B. 8080
Nim diesen Kommentar hinaus und ändere es auf 3000:3000

2024-03-20 06:49 UTC, sigristjan approved these changes

2024-04-02 09:03 UTC, fabio-liberto approved these changes

2024-04-02 09:03 UTC, merged